-- Query to check UploadedFiles table schema
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'UploadedFiles'
ORDER BY ORDINAL_POSITION;

-- Query to check FileChunks table schema
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FileChunks'
ORDER BY ORDINAL_POSITION;

-- Query to check ChunkEmbeddings table schema
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ChunkEmbeddings'
ORDER BY ORDINAL_POSITION;
